### ISSUE TITLE
[Bug] PerfectScroll.initialize is not a function

### ISSUE THREAD

**Issue by kane-mason** [creativetimofficial/ct-vue-light-bootstrap-dashboard-pro#29]
### Version
1.3.0
### Reproduction link
https://demos.creative-tim.com/vue-light-bootstrap-dashboard-pro/#/admin/overview
### Operating System
Windows 10
### Device
Dell Laptop
### Browser & Version
Chrome 84
### Steps to reproduce
1. open chrome devtools
2. navigate to provided url
3. observe error in the console
### What is expected?
No error in the console
### What is actually happening?
error in the console

---
### Solution
I think you are using a old version of the 'perfect-scrollbar' api and the code needs to be updated to make use of new api

**Comment by nft2** [comment]
I'm having the same issue on Firefox 79.

**Comment by dragosct10** [comment]
Hi, guys! We will do an update next week and then the issue will be fixed. 

Regards,
Dragos

**Comment by dragosct10** [comment]
Hi! Sorry for the late update. The product is now updated with this fix included. 

Regards,
Dragos
