### ISSUE TITLE
[Bug] None of the sweet alerts are working

### ISSUE THREAD

**Issue by kane-mason** [creativetimofficial/ct-vue-light-bootstrap-dashboard-pro#30]
### Version
1.3.0
### Reproduction link
https://demos.creative-tim.com/vue-light-bootstrap-dashboard-pro/#/components/sweet-alert
### Operating System
Windows 10
### Device
Dell Laptop
### Browser & Version
Chrome 84
### Steps to reproduce
1. open chrome dev tools
2. navigate to url provided
3. click on any of the sweel alert buttons
4. notice no result from click
5. notice error "Cannot class class as a function" in the console
### What is expected?
An alert should appear and no error in the console
### What is actually happening?
The alert does not appear and there is an error in the console

---

**Comment by sajadevo** [comment]
Hey there,

We've updated the product and this issue is fixed please updated to the latest version of the product.

Cheers,
Sajad
