### ISSUE TITLE
[Bug] Various deprecation warnings on npm install

### ISSUE THREAD

**Issue by kane-mason** [creativetimofficial/ct-vue-light-bootstrap-dashboard-pro#31]
### Version
1.3.0
### Reproduction link
http://www.cantdo.com
### Operating System
Windows 10
### Device
Dell Laptop
### Browser & Version
Chrome 84
### Steps to reproduce
1. i can't provide a url without exposing the source code
2. download/clone the repository
3. perform a 'npm install' in the project directory
4. observe deprecation warnings in the console and below:

npm WARN deprecated topojson@3.0.2: Use topojson-client, topojson-server or topojson-simplify directly.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated topojson@1.6.27: Use topojson-client, topojson-server or topojson-simplify directly.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated @hapi/joi@15.1.1: joi is leaving the @hapi organization and moving back to 'joi' (https://github.com/sideway/joi/issues/2411)
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated @hapi/address@2.1.4: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

### What is expected?
Not all the deprecations will cause a break, but some will. Ideally no deprecation warnings should appear. 
### What is actually happening?
There are deprecation warnings, a few of which will cause a break

---
### Solution
Update dependencies and useage where necessary

**Comment by dragosct10** [comment]
Hi, @kane-mason! Thanks for using our products. Yes, we will inspect to see how to fix the issues and we will come with an answer. Also for the other issues that you opened. 

Regards,
Dragos

**Comment by sajadevo** [comment]
Hey there,

We've updated the product and some of the deprecated dependencies are coming with vue and other dependencies but it doesn't cause any issue.

Cheers,
Sajad
